config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[new create show]
  end

  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
                                    message: '%<value>s is not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: (0..5).to_a }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def edit; end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create show]

  def new
    @review = Review.new
  end

  def show
    @reviews = Review.all
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-secondary'>

    <nav class="navbar navbar-light bg-light justify-content-between shadow-sm p-3 mb-5 bg-white rounded">
      <a class="navbar-brand" href='http://localhost:3000/restaurants'>Restaurants Book</a>
      <a class="navbar-brand font-italic text-muted" href='http://localhost:3000/restaurants/new'>+ New Restaurant</a>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, placeholder: 'Chinese, French, Italian, Japanese or Belgian' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class='container justify-content-center'>
  <h1 class='text-center'>Edit restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div>
    <%= link_to "Back to restaurants", restaurants_path %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class='container bg-light'>
<h1>All Restaurants</h1>
<ul class='list-group'>
<% @restaurants.each do |restaurant| %>
<li class='list-group-item'><%= link_to restaurant.name, restaurant, class: 'text-decoration-none text-black' %></li>
<% end %>
</ul>

<br>

</div>

app/views/restaurants/new.html.erb
<div class='container justify-content-center'>
  <h1 class='text-center'>New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <br>

  <div>
    <%= link_to "Back to restaurants", restaurants_path %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class='container '>
<h2><%= @restaurant.name %></h2>

<p>Address: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>

<p><%= link_to 'New Review', new_restaurant_review_path(@restaurant), class: 'btn btn-success' %></p>

<p><%= link_to 'Show Reviews', restaurant_review_path(@restaurant), class: 'btn btn-success' %></p>

<p><%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant), class: 'btn btn-success' %></p>

<p><%= button_to "Destroy Restaurant", @restaurant, method: :delete, class: 'btn btn-success' %></p>

<p><%= link_to 'Back', restaurants_path %></p>

app/views/reviews/new.html.erb
<div class='container justify-content-center'>
<h1 class='text-center'>Add review to restaurant <%= @restaurant.name %></h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, placeholder: '0 a 5'%>
  <%= f.button :submit, class: 'btn btn-primary ' %>
<% end %>

<p><%= link_to 'Back', restaurants_path %></p>
</div>

app/views/reviews/show.html.erb
<h1 class='text-center'>All Reviews - <%= @restaurant.name %></h1>
<div class='container m-3 justify-content-center'>
    <% @reviews.each do |review| %>
<div class="card d-inline bg-light mb-3" style="max-width: 18rem; max-height: 18rem;">
  <div class="card-header">Rating: <%= review.rating %> Stars</div>
      <div class="card-body">
      <h5 class="card-title">Avaliation:</h5>
    <p class="card-text"><%= review.content %></p>
</div>
</div>
    <% end %>